-- V1 Java migration preserves compatibility with legacy username columns.
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    token VARCHAR(1000) NOT NULL UNIQUE,
    expires_at TIMESTAMP(6) NOT NULL,
    revoked BOOLEAN NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS workers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    department VARCHAR(100) NOT NULL,
    phone_number VARCHAR(50) NOT NULL,
    rfid_tag VARCHAR(100) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL,
    current_latitude DOUBLE PRECISION,
    current_longitude DOUBLE PRECISION,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT,
    serial_number VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    wear_status VARCHAR(30) NOT NULL,
    last_detected_at TIMESTAMP(6),
    buzzer_enabled BOOLEAN NOT NULL,
    work_timer_enabled BOOLEAN NOT NULL,
    work_timer_started_at TIMESTAMP(6),
    work_timer_ended_at TIMESTAMP(6),
    manual_wear_override BOOLEAN NOT NULL,
    manual_wear_status VARCHAR(30),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_equipment_worker
        FOREIGN KEY (worker_id) REFERENCES workers (id)
);

CREATE TABLE IF NOT EXISTS equipment_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL,
    equipment_id BIGINT NOT NULL,
    wear_status VARCHAR(30) NOT NULL,
    issued_at TIMESTAMP(6),
    returned_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_equipment_logs_worker
        FOREIGN KEY (worker_id) REFERENCES workers (id),
    CONSTRAINT fk_equipment_logs_equipment
        FOREIGN KEY (equipment_id) REFERENCES equipment (id)
);

CREATE TABLE IF NOT EXISTS wearable_commands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL,
    equipment_id BIGINT NOT NULL,
    command_type VARCHAR(30) NOT NULL,
    command_status VARCHAR(30) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    requested_at TIMESTAMP(6),
    acknowledged_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_wearable_commands_worker
        FOREIGN KEY (worker_id) REFERENCES workers (id),
    CONSTRAINT fk_wearable_commands_equipment
        FOREIGN KEY (equipment_id) REFERENCES equipment (id)
);

CREATE TABLE IF NOT EXISTS sensor_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT,
    equipment_id BIGINT,
    sensor_type VARCHAR(30) NOT NULL,
    bpm INTEGER,
    spo2 DOUBLE PRECISION,
    body_temperature DOUBLE PRECISION,
    accelerationx DOUBLE PRECISION,
    accelerationy DOUBLE PRECISION,
    accelerationz DOUBLE PRECISION,
    gyrox DOUBLE PRECISION,
    gyroy DOUBLE PRECISION,
    gyroz DOUBLE PRECISION,
    tiltx DOUBLE PRECISION,
    tilty DOUBLE PRECISION,
    tiltz DOUBLE PRECISION,
    impact_amount DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    speed DOUBLE PRECISION,
    pressure_value INTEGER,
    lidar_front_left DOUBLE PRECISION,
    lidar_front_right DOUBLE PRECISION,
    lidar_back_left DOUBLE PRECISION,
    lidar_back_right DOUBLE PRECISION,
    lidar_side_left DOUBLE PRECISION,
    lidar_side_right DOUBLE PRECISION,
    ultrasonic_distance DOUBLE PRECISION,
    raw_payload VARCHAR(2000),
    wear_status VARCHAR(30),
    sos_pressed BOOLEAN NOT NULL,
    risk_level VARCHAR(20),
    measured_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_sensor_logs_worker
        FOREIGN KEY (worker_id) REFERENCES workers (id),
    CONSTRAINT fk_sensor_logs_equipment
        FOREIGN KEY (equipment_id) REFERENCES equipment (id)
);

CREATE TABLE IF NOT EXISTS risk_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT,
    source_type VARCHAR(20) NOT NULL,
    risk_type VARCHAR(30) NOT NULL,
    risk_level VARCHAR(20) NOT NULL,
    description VARCHAR(500) NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    status VARCHAR(20) NOT NULL,
    occurred_at TIMESTAMP(6),
    resolved_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_risk_events_worker
        FOREIGN KEY (worker_id) REFERENCES workers (id)
);

CREATE TABLE IF NOT EXISTS alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    risk_event_id BIGINT,
    worker_id BIGINT,
    title VARCHAR(200) NOT NULL,
    message VARCHAR(500) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    read_status VARCHAR(20) NOT NULL,
    read_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_alerts_risk_event
        FOREIGN KEY (risk_event_id) REFERENCES risk_events (id),
    CONSTRAINT fk_alerts_worker
        FOREIGN KEY (worker_id) REFERENCES workers (id)
);

CREATE TABLE IF NOT EXISTS drones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    serial_number VARCHAR(100) NOT NULL UNIQUE,
    model_name VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL,
    battery_percent INTEGER NOT NULL,
    current_latitude DOUBLE PRECISION,
    current_longitude DOUBLE PRECISION,
    max_flight_minutes INTEGER,
    payload_mounted BOOLEAN NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS drone_dispatches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drone_id BIGINT NOT NULL,
    risk_event_id BIGINT,
    target_latitude DOUBLE PRECISION,
    target_longitude DOUBLE PRECISION,
    dispatch_reason VARCHAR(255),
    emergency_kit_mounted BOOLEAN NOT NULL,
    emergency_kit_dropped BOOLEAN NOT NULL,
    drop_latitude DOUBLE PRECISION,
    drop_longitude DOUBLE PRECISION,
    drop_method VARCHAR(30),
    emergency_call_requested BOOLEAN NOT NULL,
    emergency_call_status VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    command_message VARCHAR(500) NOT NULL,
    dispatched_at TIMESTAMP(6),
    arrived_at TIMESTAMP(6),
    completed_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_drone_dispatches_drone
        FOREIGN KEY (drone_id) REFERENCES drones (id),
    CONSTRAINT fk_drone_dispatches_risk_event
        FOREIGN KEY (risk_event_id) REFERENCES risk_events (id)
);

CREATE TABLE IF NOT EXISTS drone_videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drone_id BIGINT NOT NULL,
    dispatch_id BIGINT,
    title VARCHAR(200),
    description VARCHAR(500),
    stream_url VARCHAR(500) NOT NULL,
    protocol VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL,
    stream_status VARCHAR(20) NOT NULL,
    started_at TIMESTAMP(6),
    ended_at TIMESTAMP(6),
    last_frame_at TIMESTAMP(6),
    width INTEGER,
    height INTEGER,
    frame_rate INTEGER,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_drone_videos_drone
        FOREIGN KEY (drone_id) REFERENCES drones (id),
    CONSTRAINT fk_drone_videos_dispatch
        FOREIGN KEY (dispatch_id) REFERENCES drone_dispatches (id)
);

CREATE TABLE IF NOT EXISTS drone_drop_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drone_dispatch_id BIGINT NOT NULL,
    drone_id BIGINT NOT NULL,
    worker_id BIGINT,
    risk_event_id BIGINT,
    drop_method VARCHAR(30) NOT NULL,
    target_latitude DOUBLE PRECISION,
    target_longitude DOUBLE PRECISION,
    actual_drop_latitude DOUBLE PRECISION,
    actual_drop_longitude DOUBLE PRECISION,
    obstacle_detected BOOLEAN NOT NULL,
    lidar_front_left DOUBLE PRECISION,
    lidar_front_right DOUBLE PRECISION,
    lidar_back_left DOUBLE PRECISION,
    lidar_back_right DOUBLE PRECISION,
    lidar_side_left DOUBLE PRECISION,
    lidar_side_right DOUBLE PRECISION,
    drop_status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_drone_drop_logs_dispatch
        FOREIGN KEY (drone_dispatch_id) REFERENCES drone_dispatches (id),
    CONSTRAINT fk_drone_drop_logs_drone
        FOREIGN KEY (drone_id) REFERENCES drones (id),
    CONSTRAINT fk_drone_drop_logs_worker
        FOREIGN KEY (worker_id) REFERENCES workers (id),
    CONSTRAINT fk_drone_drop_logs_risk_event
        FOREIGN KEY (risk_event_id) REFERENCES risk_events (id)
);

CREATE INDEX IF NOT EXISTS idx_equipment_worker ON equipment (worker_id);
CREATE INDEX IF NOT EXISTS idx_equipment_logs_worker ON equipment_logs (worker_id);
CREATE INDEX IF NOT EXISTS idx_sensor_logs_worker_measured ON sensor_logs (worker_id, measured_at);
CREATE INDEX IF NOT EXISTS idx_risk_events_worker_status ON risk_events (worker_id, status);
CREATE INDEX IF NOT EXISTS idx_alerts_read_status ON alerts (read_status);
CREATE INDEX IF NOT EXISTS idx_drone_dispatches_risk_event ON drone_dispatches (risk_event_id);
CREATE INDEX IF NOT EXISTS idx_drone_videos_dispatch ON drone_videos (dispatch_id);
